# Generated by Django 4.2.5 on 2024-03-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_video_delete_emailre'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='discription',
            field=models.TextField(default=''),
        ),
    ]
