# Generated by Django 4.2.5 on 2024-03-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_project_projectlink_delete_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProjectLink',
        ),
    ]
